services:
  app:
    image: api
    command: sh -c 'node /app/server.js'
    ports:
      - 127.0.0.1:3333:3333
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB_NAME: todoo

  mysql:
    image: mysql:8.0
    volumes:
      - todo-mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todoo

volumes:
  todo-mysql:
